name: chocolatine

permissions:
  contents: read

on:
  push:
    branches-ignore:
      - 'no-ga/*'
  pull_request:
    branches-ignore:
      - 'no-ga/*'
  workflow_dispatch:

env:
  MIRROR_SSH_URL: ${{ vars.MIRROR_SSH_URL }}
  EXECUTABLES: ${{ vars.EXECUTABLES }}

jobs:
  check_compilation_and_coding_style:
    runs-on: ubuntu-24.04
    container: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: 0
      - name: Checkout repository && banana-check-repo
        run: banana-check-repo .
      - name: compile with make
        run: make CC=epiclang 2>&1 | tee log.txt
        timeout-minutes: 2
      - name: Error Annotation
        run: |
          awk -F':' 'file=$1; print "file " file; line=$2; print "line " line; colum=$3; print "colum " column; type=$4'
          print file
          if (type == "error")' {
            printf "::error file=%s,line=%s,col=%s::%s\n", file", line, colum, message)

      - name: Cleaning of the repository
        run: make clean
      - name: Display coding style errors
        run: |
          echo "Plus tard seront affichés les erreurs de coding style"

  run_tests:
    runs-on: ubuntu-24.04
    container: epitechcontent/epitest-docker
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          fetch-depth: 0
      - name: Make test_run
        run: make tests_run
        timeout-minutes: 2

  push_to_mirror:
    if: github.event_name == 'push'
    runs-on: ubuntu-24.04
    container: epitechcontent/epitest-docker
    steps:
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_SSH_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
