name: chocolatine

permissions:
  contents: read

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  MIRROR_SSH_URL: ${{ vars.MIRROR_SSH_URL }}
  EXECUTABLES: ${{ vars.EXECUTABLES }}

jobs:
  check_compilation_and_coding_style:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
      - name: Checkout repository
        run: banana-check-repo

      - name: compile with make
        run: make
        timeout-minutes: 2
        env:
          CC: epiclang
